services:
  mysql:
    image: mysql:8.0
    container_name: mysql-bind-mount-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Sql@054003
      MYSQL_DATABASE: bind_mount_db
    ports:
      - "3306:3306"
    volumes:
      - /home/mysql_bind_mount_data:/var/lib/mysql # Absolute pate, or
      #- ./mysql_bind_mount_data:/var/lib/mysql # Where `mysql_bind_mount_data` in local/host in home's directory.

  nodeapp:
    build:
      context: ./app
    image: nodejs-express  # 👈 Custom image name here
    container_name: nodejs-app-container
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: Sql@054003
      DB_NAME: bind_mount_db
