services:
  mysql:
    image: mysql:8.0
    container_name: mysql-server-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Sql@054003
      MYSQL_DATABASE: bind_mount_db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  nodeapp:
    build:
      context: ./app
    image: nodejs-express  # 👈 Custom image name here
    container_name: nodejs-app-container
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: Sql@054003
      DB_NAME: bind_mount_db
