services:
  nodeapp:
    build:
      context: ./app
    image: nodejs-express
    container_name: nodejs-app-container
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: Sql@054003
      DB_NAME: volume_mount_db

  mysql:
    image: mysql:8.0
    container_name: mysql-volume-mount-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Sql@054003
      MYSQL_DATABASE: volume_mount_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql # here `mysql_data` docker volume in container

volumes:
  mysql_data:
    name: mysql_data # declare the named volume in docker
# if the name `mysql_data` change then it will be bind mount.
